name: Renovate Fix

on: workflow_dispatch

permissions:
  contents: write

jobs:
  renovate-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.name "github actions"
      - run: git config --global user.email "actions@github.com"

      - run: date > changing-file.txt

      - run: |
          git add .
          git commit -m "Automatic Renovate Fix" || exit 0
          git push
